/**
 * Deterministic demo catalogue.
 *
 * These are invented entries used by demo mode and the test suite - they are
 * not real releases and are never presented as live results. `tone`/`waveform`
 * drive the synthesised audio so demo playback is real audio, not a fake
 * progress bar.
 */
export const SAMPLE_TRACKS = Object.freeze([
  {
    id: 'demo-001',
    title: 'Neon Arcade',
    artist: 'Vector Field',
    album: 'Parallax',
    duration: 95,
    genre: 'electronic',
    year: 2021,
    tone: 261.63,
    waveform: 'sine',
  },
  {
    id: 'demo-002',
    title: 'Slow Terminal',
    artist: 'Vector Field',
    album: 'Parallax',
    duration: 142,
    genre: 'electronic',
    year: 2021,
    tone: 293.66,
    waveform: 'triangle',
  },
  {
    id: 'demo-003',
    title: 'Paper Lanterns',
    artist: 'Hana Ito',
    album: 'Quiet Rooms',
    duration: 188,
    genre: 'ambient',
    year: 2019,
    tone: 329.63,
    waveform: 'sine',
  },
  {
    id: 'demo-004',
    title: 'Low Tide',
    artist: 'Hana Ito',
    album: 'Quiet Rooms',
    duration: 204,
    genre: 'ambient',
    year: 2019,
    tone: 349.23,
    waveform: 'sine',
  },
  {
    id: 'demo-005',
    title: 'Copper Wires',
    artist: 'The Standing Wave',
    album: 'Signal Hill',
    duration: 176,
    genre: 'rock',
    year: 2020,
    tone: 392.0,
    waveform: 'square',
  },
  {
    id: 'demo-006',
    title: 'Signal Hill',
    artist: 'The Standing Wave',
    album: 'Signal Hill',
    duration: 231,
    genre: 'rock',
    year: 2020,
    tone: 440.0,
    waveform: 'square',
  },
  {
    id: 'demo-007',
    title: 'Nightbus',
    artist: 'The Standing Wave',
    album: 'Signal Hill',
    duration: 118,
    genre: 'rock',
    year: 2020,
    tone: 493.88,
    waveform: 'triangle',
  },
  {
    id: 'demo-008',
    title: 'Blue Hour Waltz',
    artist: 'Marguerite Lowe',
    album: 'Six Rooms',
    duration: 167,
    genre: 'jazz',
    year: 2018,
    tone: 523.25,
    waveform: 'sine',
  },
  {
    id: 'demo-009',
    title: 'Two Left Shoes',
    artist: 'Marguerite Lowe',
    album: 'Six Rooms',
    duration: 145,
    genre: 'jazz',
    year: 2018,
    tone: 587.33,
    waveform: 'triangle',
  },
  {
    id: 'demo-010',
    title: 'Cassette Sunrise',
    artist: 'Pale Orbit',
    album: 'Fold',
    duration: 99,
    genre: 'lofi',
    year: 2022,
    tone: 220.0,
    waveform: 'sine',
  },
  {
    id: 'demo-011',
    title: 'Fold',
    artist: 'Pale Orbit',
    album: 'Fold',
    duration: 213,
    genre: 'lofi',
    year: 2022,
    tone: 246.94,
    waveform: 'triangle',
  },
  {
    id: 'demo-012',
    title: 'Static Garden',
    artist: 'Pale Orbit',
    album: 'Fold',
    duration: 158,
    genre: 'lofi',
    year: 2022,
    tone: 196.0,
    waveform: 'sine',
  },
  {
    id: 'demo-013',
    title: 'Winter Count',
    artist: 'Ardal Finn',
    album: 'Longhand',
    duration: 224,
    genre: 'folk',
    year: 2017,
    tone: 174.61,
    waveform: 'triangle',
  },
  {
    id: 'demo-014',
    title: 'Longhand',
    artist: 'Ardal Finn',
    album: 'Longhand',
    duration: 191,
    genre: 'folk',
    year: 2017,
    tone: 164.81,
    waveform: 'sine',
  },
  {
    id: 'demo-015',
    title: 'Harbour Lights',
    artist: 'Ardal Finn',
    album: 'Longhand',
    duration: 112,
    genre: 'folk',
    year: 2017,
    tone: 146.83,
    waveform: 'sine',
  },
  {
    id: 'demo-016',
    title: 'Grid Nine',
    artist: 'Consolidated Motion',
    album: 'Rolling Stock',
    duration: 138,
    genre: 'techno',
    year: 2023,
    tone: 130.81,
    waveform: 'square',
  },
  {
    id: 'demo-017',
    title: 'Rolling Stock',
    artist: 'Consolidated Motion',
    album: 'Rolling Stock',
    duration: 265,
    genre: 'techno',
    year: 2023,
    tone: 155.56,
    waveform: 'square',
  },
  {
    id: 'demo-018',
    title: 'Tape Delay',
    artist: 'Consolidated Motion',
    album: 'Rolling Stock',
    duration: 87,
    genre: 'techno',
    year: 2023,
    tone: 185.0,
    waveform: 'triangle',
  },
  {
    id: 'demo-019',
    title: 'Prelude in Dust',
    artist: 'Orsolya Bede',
    album: 'Etudes for Empty Halls',
    duration: 246,
    genre: 'classical',
    year: 2016,
    tone: 277.18,
    waveform: 'sine',
  },
  {
    id: 'demo-020',
    title: 'Etude No. 4',
    artist: 'Orsolya Bede',
    album: 'Etudes for Empty Halls',
    duration: 179,
    genre: 'classical',
    year: 2016,
    tone: 311.13,
    waveform: 'sine',
  },
]);

/** Convenience for tests that want a single known track. */
export const SAMPLE_TRACK_IDS = SAMPLE_TRACKS.map((t) => t.id);
